# Generated by Django 3.1.4 on 2020-12-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
