# Generated by Django 3.1.4 on 2020-12-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='removed',
            field=models.NullBooleanField(),
        ),
    ]
