# Generated by Django 3.1.4 on 2020-12-31 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201231_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 14, 16, 10, 764313)),
        ),
    ]
