# Generated by Django 3.1.4 on 2020-12-31 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20201231_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 14, 18, 35, 596608)),
        ),
    ]
