# Generated by Django 3.1.4 on 2020-12-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20201231_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(db_column='author_age', null=True),
        ),
    ]
