# Generated by Django 3.1.4 on 2020-12-31 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20201231_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
