# Generated by Django 3.1.4 on 2020-12-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_author_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
