# Generated by Django 3.1.6 on 2021-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('length', models.FloatField(max_length=100)),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
    ]
