# Generated by Django 3.1.4 on 2021-01-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210118_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='context',
            field=models.TextField(default=''),
        ),
    ]
