# Generated by Django 3.1.4 on 2021-01-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articles_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('telephone', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
